server:
  port: 8082

spring:
  application:
    name: payment

# Настройки Eureka Client
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

  profiles:
    active: eclient

  config:
    import: configserver:http://localhost:8888

    #management:
 # endpoints:
  #  web:
   #   exposure:
    #    include: metrics,prometheus

